### PR TITLE
Move assets to a structure conducive of a third-party solution. (2/2)

### PR DESCRIPTION
**Pull request by djohns451**

### CODE REVIEW

**Review by MarcusElg — COMMENTED** [review]
If you think this way is the right to go then it probably is but there are 2 issues: a) How do I fix my github desktop to follow this structure and b) Could you do a pull request based on the intersections branch, this way there won't be an enormous problem when that branch will be merged to master

**Comment by djohns451** [comment]
- a) You can just _pull_ the changes, once committed. If you've got local changes, you'll want to stash them before you update your local repository.

- b) Sure, it'll be updated soon.

**Comment by MarcusElg** [comment]
a) You'll have to explain that a bit more. In my local github reposistry the files are in RoadCreator/Assets/Resourcources (or something similar). How should I suddenly make it ignore the first folder but magicly keep the files?

b) Is this ready to merge? Tell me when it is and I will.

**Comment by embeddedt** [comment]
@MCrafterzz From what I can tell @djohns451 moved everything out of `Road Creator` in his repository. As soon as you download his copy by pulling in GitHub Desktop, it will move the files for you as well.

**Comment by djohns451** [comment]
a) That depends on whether or not you have any local uncommitted changes.
Do you have any of those?

b) It's ready to pull.

**Comment by djohns451** [comment]
@embeddedt I think he's talking about remapping his changes on top of my
changes.

**Comment by embeddedt** [comment]
@djohns451 Ok. So he just merged your changes into `proceduralintersections`. Now he should pull `proceduralintersections`, and then push `proceduralintersections`.

**Comment by embeddedt** [comment]
When he pulls `proceduralintersections` it will merge his local changes with yours. Then `git push` would push the merged tree to GitHub.

**Comment by embeddedt** [comment]
@djohns451 @MCrafterzz But, looking at this specific case, there could be an issue because you have moved the files which he was working on. That might require some manual merging... I'm not sure if Git is smart enough to handle it in this case.

**Comment by djohns451** [comment]
@embeddedt Eww...

**Comment by djohns451** [comment]
All that __should__ need be done is that their new commits need rebased onto my commits.

**Comment by djohns451** [comment]
@MCrafterzz Do you have access to the command-line `git` client?

**Comment by embeddedt** [comment]
@djohns451 Should we make a Gitter room? This might get long...

**Comment by djohns451** [comment]
@embeddedt Yeah, that's better.

**Comment by embeddedt** [comment]
@djohns451 Ok, I think you'll have to make it as you are a "Contributor".

**Comment by djohns451** [comment]
See the README in my fork of the project -- I've got a room setup.

**Comment by embeddedt** [comment]
@djohns451 I'm there!

**Comment by djohns451** [comment]
@MCrafterzz `git push -b [whatever branch your commits are on] https://github.com/djohns451/roadcreator`

**Comment by djohns451** [comment]
(Or use SSH if you have that setup.)

**Pull request merged**
